# Complexity analysis

- https://www.ics.uci.edu/~pattis/ICS-33/lectures/complexitypython.txt
- https://wiki.python.org/moin/TimeComplexity

# ``.remove(val)``, ``del list[pos]``, ``.pop(pos)``  

In [1]:
a = [0, 2, 3, 2]
a.remove(2)
print(a)

a = [0, 2, 3, 2]
del a[1]
print(a)

a = [0, 2, 3, 2]
a.pop(1)
print(a)

[0, 3, 2]
[0, 3, 2]
[0, 3, 2]


# ``.append()``, ``.extend()``, ``.insert(pos, val)`` 

In [16]:
d = [1, 2, 3, 4, 5]

#append(element): add the element
d.append(5)
d[len(d):] = [6]

#extend(list): add lists
d.extend([7, 8, 9])
d[len(d):] = [10, 11, 12, 13]
d += [14, 15, 16]


# insert
d.insert(0, 0)
d.insert(0, -1)
print(d)

[-1, 0, 1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


# ``.index()``, ``.count() ``

In [8]:
#count(item): count the number of times that appears
print( d.count(1) )

#.index()
d = [1,2,3,3,3,3]
print( d.index(3) )

1
2


# Indexing 

In [2]:
a = list(range(20))
print( a[4:15:3])
print( a[::-1])
print( a[-1:0:-1])
print( a[-3:3:-2])

[4, 7, 10, 13]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[17, 15, 13, 11, 9, 7, 5]


# Matrices

In [15]:
a = [[0]*3]*3
a[0][0] = 1
print(a)

b = [[0]*3 for i in range(3)]
b[0][0] = 1
print(b)

c = [[[0]*3 for i in range(3)] for j in range(3)]
c[0][0][0] = 1
print(c)

[[1, 0, 0], [1, 0, 0], [1, 0, 0]]
[[1, 0, 0], [0, 0, 0], [0, 0, 0]]
[[[1, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]


In [12]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(a[:][0])

import numpy as np
b = np.array(a)
print(b[:][0])
print(b[:,0])

[1, 2, 3]
[1 2 3]
[1 2 3]
[1 4 7]


# lists - strings

In [3]:
a = 'mr. sanchez is great'
a.split(' ')
print(a)

mr. sanchez is great


In [1]:
d = list(range(-5,5,1))
print(d)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


In [2]:
a = [1, 2, 3]
print(str(a))

[1, 2, 3]


# Multiplication 

In [21]:
a = [1,2,3,4]
a = a*2
a[-1] = 5
print( a )

[1, 2, 3, 4, 1, 2, 3, 5]


In [12]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']