# List 

# List.sort()

https://docs.python.org/3.6/library/stdtypes.html?highlight=sort#list.sort

it is Timsort - stable - $\Omega(n) O( n log n) - Space O(n) $

In [2]:
a = [1,3,5,4,6,8,7,9,2]
a.sort()
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
b = [ (1,2,3,4,5,6,7,8,9) , [1] , "hello", "my","darling"]
b.sort(key=len)
print(b)

[[1], 'my', 'hello', 'darling', (1, 2, 3, 4, 5, 6, 7, 8, 9)]


In [16]:
c = ["hello", "my","darling"]

# option 1
c.sort( key= lambda word: word[-1], reverse=True)
print(b)

# option 2
def functionaux(listin):
    return listin[0]
c.sort( key = functionaux)
print(c)

['my', 'hello', 'darling']
['darling', 'hello', 'my']


# List = sorted(List)

https://docs.python.org/3.6/library/functions.html#sorted

In [1]:
d = [ 1,2,3,9,8,7,6,5,4]
f = sorted(d)
print(d)
print(f)

[1, 2, 3, 9, 8, 7, 6, 5, 4]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


# Related lists

In [4]:
x = [3, 2, 1]
y = [5, 4, 6]

map_sorted = sorted(zip(x, y), key=lambda item: item[0])

unzipped = zip(*map_sorted)

xsorted, ysorted = map(list, unzipped)

print(xsorted, ysorted)

[1, 2, 3] [6, 4, 5]


# Numpy 

In [4]:
import numpy as np


a = np.array( [1,4,3,2,7,6,5,8,9] )
a = [1,4,3,2,7,6,5,8,9]

kindofsort = 'quicksort'     # default
#kindofsort = 'stable'
#kindofsort = 'heapsort'
#kindofsort = 'mergesort'

asorted = np.sort(a, kind=kindofsort)
print(asorted)

[1 2 3 4 5 6 7 8 9]


# Numpy - sort by columns 

In [7]:
data = np.array([[3,6], [1,5], [2,4]])

indexes = np.argsort( data[:,0] )
data_sorted = data[ indexes ]

print(data)
print(data_sorted)

[[3 6]
 [1 5]
 [2 4]]
[[1 5]
 [2 4]
 [3 6]]
